name: atmonitor
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  uuid:
  firebase_storage:
  image_picker:
  camera:
  fluttertoast: ^2.0.7
  cupertino_icons: ^0.1.2
  firebase_database: ^1.0.4
  firebase_auth: ^0.5.20
  google_sign_in: ^3.0.5
  firebase_core: any
  flushbar: ^0.9.0
  shared_preferences: ^0.4.2
  pull_to_refresh: ^1.1.5
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Black.ttf
        - asset: fonts/WorkSans-Bold.ttf
        - asset: fonts/WorkSans-ExtraBold.ttf
        - asset: fonts/WorkSans-ExtraLight.ttf
        - asset: fonts/WorkSans-Light.ttf
        - asset: fonts/WorkSans-Medium.ttf
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-SemiBold.ttf
        - asset: fonts/WorkSans-Thin.ttf

  uses-material-design: true
  assets:
  - images/radar-chart.png
  - images/atmonitor.png
  - images/logoatmonitor.png
  - images/logobagus.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
